repos:
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.28.0
    hooks:
      - id: yapf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
  # Currently there is an issue with this hook.
  # - repo: https://github.com/FalconSocial/pre-commit-python-sorter
  #   rev: 1.0.4
  #   hooks:
  #   - id: python-import-sorter
